
[clientes]

campo[]     = "-"
etiqueta[]  = "-"
ayuda[]     = ""
error[]     = ""

campo[]     = "direccion"
etiqueta[]  = "Dirección"
ayuda[]     = "Escriba su Dirección completa"
error[]     = ""

campo[]     = "id"
etiqueta[]  = "Id"
ayuda[]     = ""
error[]     = ""

campo[]     = "intermediario_id"
etiqueta[]  = "Intermediario"
ayuda[]     = ""
error[]     = ""

campo[]     = "nombre"
etiqueta[]  = "Nombre"
ayuda[]     = "Escriba el nombre completo"
error[]     = "Este campo no se puede dejar vacío"

campo[]     = "telefono"
etiqueta[]  = "Teléfono"
ayuda[]     = ""
error[]     = ""


[intermediarios]

campo[]     = "-"
etiqueta[]  = "-"
ayuda[]     = ""
error[]     = ""

campo[]     = "id"
etiqueta[]  = "Id"
ayuda[]     = ""
error[]     = ""

campo[]     = "nombre"
etiqueta[]  = "Nombre"
ayuda[]     = ""
error[]     = ""


[productos]

campo[]     = "-"
etiqueta[]  = "-"
ayuda[]     = ""
error[]     = ""

campo[]     = "id"
etiqueta[]  = "Id"
ayuda[]     = ""
error[]     = ""

campo[]     = "nombre"
etiqueta[]  = "Nombre"
ayuda[]     = ""
error[]     = ""

campo[]     = "unidadcompra"
etiqueta[]  = "Unidadcompra"
ayuda[]     = ""
error[]     = ""


[proveedores]

campo[]     = "-"
etiqueta[]  = "-"
ayuda[]     = ""
error[]     = ""

campo[]     = "apodo"
etiqueta[]  = "Apodo"
ayuda[]     = ""
error[]     = ""

campo[]     = "id"
etiqueta[]  = "Id"
ayuda[]     = ""
error[]     = ""

campo[]     = "intermediario"
etiqueta[]  = "Intermediario"
ayuda[]     = ""
error[]     = ""

campo[]     = "nombre"
etiqueta[]  = "Nombre"
ayuda[]     = ""
error[]     = ""

campo[]     = "productos"
etiqueta[]  = "Productos que vende"
ayuda[]     = ""
error[]     = ""

campo[]     = "ubicacion"
etiqueta[]  = "Ubicación"
ayuda[]     = ""
error[]     = ""


[usuarios]

campo[]     = "-"
etiqueta[]  = "-"
ayuda[]     = ""
error[]     = ""

campo[]     = "activo"
etiqueta[]  = "Activo"
ayuda[]     = ""
error[]     = ""

campo[]     = "clave"
etiqueta[]  = "Clave"
ayuda[]     = ""
error[]     = ""

campo[]     = "email"
etiqueta[]  = "Email"
ayuda[]     = ""
error[]     = ""

campo[]     = "id"
etiqueta[]  = "Id"
ayuda[]     = ""
error[]     = ""

campo[]     = "nivel"
etiqueta[]  = "Nivel"
ayuda[]     = ""
error[]     = ""

campo[]     = "nombre"
etiqueta[]  = "Nombre"
ayuda[]     = ""
error[]     = ""

