[usuarios]

campo[]     = "-"
etiqueta[]  = "-"
ayuda[]     = ""
error[]     = ""

campo[]     = "activo"
etiqueta[]  = "Activo"
ayuda[]     = ""
error[]     = ""

campo[]     = "clave"
etiqueta[]  = "Clave"
ayuda[]     = ""
error[]     = ""

campo[]     = "clave_ver"
etiqueta[]  = "Repita la clave, por favor"
ayuda[]     = ""
error[]     = ""

campo[]     = "email"
etiqueta[]  = "Email"
ayuda[]     = ""
error[]     = ""

campo[]     = "id"
etiqueta[]  = "Login"
ayuda[]     = ""
error[]     = ""

campo[]     = "nivel"
etiqueta[]  = "Nivel"
ayuda[]     = ""
error[]     = ""

campo[]     = "nombre"
etiqueta[]  = "Nombre"
ayuda[]     = ""
error[]     = ""


[empleados]

campo[]     = "id"
etiqueta[]  = "Cédula de Identidad"
ayuda[]     = "Escribe la cédula sin usar puntos ni letras."
error[]     = "La cédula DEBE escribirse en este campo."


campo[]     = "nombre"
etiqueta[]  = "Nombres"
ayuda[]     = ""
error[]     = ""


campo[]     = "apellido"
etiqueta[]  = "Apellidos"
ayuda[]     = ""
error[]     = ""


campo[]     = "direccion"
etiqueta[]  = "Dirección"
ayuda[]     = "Dirección de habitación"
error[]     = ""


campo[]     = "telefono"
etiqueta[]  = "Teléfono"
ayuda[]     = ""
error[]     = ""


campo[]     = "f_ingreso"
etiqueta[]  = "Fecha de ingreso"
ayuda[]     = ""
error[]     = ""


campo[]     = "condicion"
etiqueta[]  = "Condición del contrato"
ayuda[]     = ""
error[]     = ""


campo[]     = "f_vence"
etiqueta[]  = "Fecha de vencimiento"
ayuda[]     = ""
error[]     = ""


campo[]     = "cargo_id"
etiqueta[]  = "Cargo"
ayuda[]     = "Cargo del empleado"
error[]     = "Seleccione el cargo"

campo[]     = "cargo"
etiqueta[]  = "Cargo"
ayuda[]     = "Cargo del empleado"
error[]     = "Seleccione el cargo"


campo[]     = "departamento_id"
etiqueta[]  = "Departamento"
ayuda[]     = ""
error[]     = ""


campo[]     = "salario"
etiqueta[]  = "Salario (en Bs)"
ayuda[]     = ""
error[]     = ""

campo[]     = "asignacion"
etiqueta[]  = "Asignaciones (en Bs)"
ayuda[]     = ""
error[]     = ""

campo[]     = "deduccion"
etiqueta[]  = "Deducciones (en Bs)"
ayuda[]     = ""
error[]     = ""


campo[]     = "num_cuenta"
etiqueta[]  = "Nº de cuenta Nómina"
ayuda[]     = ""
error[]     = ""


campo[]     = "num_hijo"
etiqueta[]  = "Cantidad de hijos"
ayuda[]     = ""
error[]     = ""





[departamentos]

campo[]     = "id"
etiqueta[]  = "Id del departamento"
ayuda[]     = "Id."
error[]     = "Error en ID."


campo[]     = "departamento"
etiqueta[]  = "Nombre del Departamento"
ayuda[]     = "Ayuda del departamento"
error[]     = "Error del departamento"



[cargos]

campo[]     = "id"
etiqueta[]  = "Id del cargo"
ayuda[]     = "Id."
error[]     = "Error en ID."


campo[]     = "cargo"
etiqueta[]  = "Nombre del cargo"
ayuda[]     = "No dejar en blanco "
error[]     = "llene el campo"


[asigdeds]

campo[]     = "id"
etiqueta[]  = "Código"
ayuda[]     = "Id."
error[]     = "Error en ID."

campo[]     = "nombre"
etiqueta[]  = "Nombre"
ayuda[]     = "Ayuda"
error[]     = "Error "

campo[]     = "tipo_ad"
etiqueta[]  = "Tipo de asignación o deducción"
ayuda[]     = "Ayuda"
error[]     = "Error"

campo[]     = "tipo"
etiqueta[]  = "Tipo"
ayuda[]     = "Ayuda"
error[]     = "Error"

campo[]     = "valor"
etiqueta[]  = "Valor"
ayuda[]     = "Ayuda"
error[]     = "Error"

[ad_periodos]

campo[]     = "id"
etiqueta[]  = "Código"
ayuda[]     = "Id."
error[]     = "Error en ID."

campo[]     = "empleado_id"
etiqueta[]  = "Empleado"
ayuda[]     = "Id."
error[]     = "Error en ID."

campo[]     = "periodo_id"
etiqueta[]  = "Período"
ayuda[]     = "Id."
error[]     = "Error en ID."

campo[]     = "asigded_id"
etiqueta[]  = "Tipo de asignación o deducción"
ayuda[]     = "Id."
error[]     = "Error en ID."

campo[]     = "monto"
etiqueta[]  = "Monto en Bs"
ayuda[]     = "Id."
error[]     = "Error en ID."


[periodos]

campo[]     = "id"
etiqueta[]  = "Código"
ayuda[]     = "Id."
error[]     = "Error en ID."

campo[]     = "f_inicio"
etiqueta[]  = "fecha de inicio"
ayuda[]     = "Id."
error[]     = "Error en ID."

campo[]     = "f_final"
etiqueta[]  = "fecha final"
ayuda[]     = "Id."
error[]     = "Error en ID."

campo[]     = "n_dias_lab"
etiqueta[]  = "Días laborables"
ayuda[]     = ""
error[]     = ""

campo[]     = "periodo"
etiqueta[]  = "Período de Pago"
ayuda[]     = "Seleccione el período de pago"
error[]     = ""

campo[]     = "anyo"
etiqueta[]  = "Año"
ayuda[]     = "Seleccione el año"
error[]     = ""

campo[]     = "condicion"
etiqueta[]  = "Condición"
ayuda[]     = "ABIERTO: En proceso. CERRADO: Finalizado"
error[]     = ""

campo[]     = "mes"
etiqueta[]  = "Mes"
ayuda[]     = "Seleccione el mes"
error[]     = ""

campo[]     = "n_lunes"
etiqueta[]  = "Número de lunes"
ayuda[]     = "Cantidad de lunes en el período"
error[]     = ""

campo[]     = "tipo_periodo"
etiqueta[]  = "Tipo de periodo"
ayuda[]     = "Seleccione el tipo de período apropiado"
error[]     = ""

[salarios]

campo[]     = "-"
etiqueta[]  = "Tabla Salarios"
ayuda[]     = "En esta tabla guardamos las tablas de salarios"
error[]     = ""


campo[]     = "id"
etiqueta[]  = "Código"
ayuda[]     = "Id."
error[]     = "Error en ID."

campo[]     = "f_inicio"
etiqueta[]  = "fecha de inicio"
ayuda[]     = "Id."
error[]     = "Error en ID."

campo[]     = "cargo_id"
etiqueta[]  = "Cargo"
ayuda[]     = "Cargo."
error[]     = "Error en Cargo."

campo[]     = "salario_diario"
etiqueta[]  = "Salario diario (SD)"
ayuda[]     = "En Bs. con dos decimales"
error[]     = ""

campo[]     = "salario_semanal"
etiqueta[]  = "Salario semanal (SS)"
ayuda[]     = "En Bs. con dos decimales"
error[]     = ""

campo[]     = "salario_quincenal"
etiqueta[]  = "Salario quincenal (SQ)"
ayuda[]     = "En Bs. con dos decimales"
error[]     = ""

campo[]     = "salario_mensual"
etiqueta[]  = "Salario mensual (SM)"
ayuda[]     = "En Bs. con dos decimales"
error[]     = ""

